# This is a basic workflow to help you get started with Actions

name: Sample Workflow

permissions:
  id-token: write
  attestations: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: "**"
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  init:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: init
    strategy:
      matrix:
        user: ["user1", "user2", "user3"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
          hi: ${{ format('Hello, {0}!', matrix.user) }}
        run: echo $hi

      - name: Run a one-line script
        env:
          hi: ${{ format('Hello, {0}!', matrix.user) }}
        run: echo "${hi}" > artifact_${{ github.job }}.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('build-{0}', matrix.user) }}
          path: |
            artifact_${{ github.job }}.txt
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: artifact_${{ github.job }}.txt
    
